import type { Metadata } from 'next';
import './globals.css';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { ReactNode } from 'react';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen text-white font-sans overflow-x-hidden">
        {/* Background image (behind everything) */}
        <div className="fixed top-0 left-0 w-screen h-screen z-0">
          <Image
            src="/forest.png"
            alt="Forest pixel art"
            fill
            priority
            className="object-cover object-center"
            style={{ imageRendering: 'pixelated' }}
          />
        </div>

        {/* Overlay to slightly darken the image (optional) */}
        <div className="fixed inset-0 bg-black/60 z-0" />

        {/* Main content above the background */}
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
